name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build outputs (APK)
      uses: actions/upload-artifact@v4
      with:
        name: app-build # Názov artefaktu s APK
        path: composeApp/build/outputs/ # Cesta k APK (môže obsahovať viac súborov/adresárov)

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v4

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1 # Zostaví Jekyll stránku
      with:
        source: ./ # Koreňový adresár ako zdroj Jekyll stránky
        destination: ./_site # Cieľový adresár pre zostavenú stránku

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3 # Nahrá zostavenú stránku ako artefakt pre nasadenie

  deploy:
    needs: build # Spustí sa až po úspešnom dokončení 'build' jobu
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Potrebné na nasadenie na GitHub Pages
      id-token: write   # Potrebné pre OpenID Connect s GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL nasadenej stránky
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Nasadí artefakt na GitHub Pages
